# Generated by Django 2.2.7 on 2019-11-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinewise', '0002_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinewise.Node')),
            ],
        ),
    ]
