# Generated by Django 2.2.7 on 2019-11-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinewise', '0005_delete_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
